Update Makefile, vendor to get tests passing again

diff --git a/vendor/github.com/coreos/etcd/test b/vendor/github.com/coreos/etcd/test
--- a/vendor/github.com/coreos/etcd/test
+++ b/vendor/github.com/coreos/etcd/test
@@ -10,6 +10,8 @@
 # PKG=snap ./test
 set -e
 
+source ./build
+
 # TODO: 'client' pkg fails with gosimple from generated files
 # TODO: 'rafttest' is failing with unused
 GOSIMPLE_UNUSED_PATHS=$(go list ./... | sed -e 's/github.com\/coreos\/etcd\///g' | grep -vE 'cmd|vendor|rafttest|github.com/coreos/etcd$|client$')
@@ -17,19 +19,12 @@ GOSIMPLE_UNUSED_PATHS=$(go list ./... | sed -e 's/github.com\/coreos\/etcd\///g'
 # Invoke ./cover for HTML output
 COVER=${COVER:-"-cover"}
 
-GO_BUILD_FLAGS="-a -v"
-source ./build
-
-# Set up gopath so tests use vendored dependencies
-export GOPATH=${PWD}/gopath
-rm -rf $GOPATH/src
-mkdir -p $GOPATH
-ln -s ${PWD}/cmd/vendor $GOPATH/src
-
 # Hack: gofmt ./ will recursively check the .git directory. So use *.go for gofmt.
-PKGS=`ls pkg/*/*go  | cut -f1,2 -d/ | sort | uniq`
-TESTABLE_AND_FORMATTABLE="auth client clientv3 discovery error etcdctl/ctlv2 etcdctl/ctlv3 etcdmain etcdserver etcdserver/auth etcdserver/api/v2http etcdserver/api/v2http/httptypes etcdserver/api/v3rpc etcdserver/api/v3rpc/rpctypes $PKGS proxy/httpproxy proxy/tcpproxy raft snap mvcc mvcc/backend store version wal rafthttp"
-FORMATTABLE="$TESTABLE_AND_FORMATTABLE *.go etcdctl/ integration clientv3/integration e2e alarm"
+IGNORE_PKGS="(cmd|vendor|etcdserverpb|rafttest)"
+INTEGRATION_PKGS="(integration|e2e|contrib|functional-tester)"
+TEST_PKGS=`find . -name \*_test.go | while read a; do dirname $a; done | sort | uniq | egrep -v "$IGNORE_PKGS" | sed "s|\./||g"`
+FORMATTABLE=`find . -name \*.go | while read a; do echo $(dirname $a)/"*.go"; done | sort | uniq | egrep -v "$IGNORE_PKGS" | sed "s|\./||g"`
+TESTABLE_AND_FORMATTABLE=`echo "$TEST_PKGS" | egrep -v "$INTEGRATION_PKGS"`
 
 # user has not provided PKG override
 if [ -z "$PKG" ]; then
@@ -91,6 +86,9 @@ function fmt_tests {
 
 	echo "Checking 'go tool vet -shadow'..."
 	for path in $FMT; do
+		if [ "${path##*.}" != "go" ]; then
+			path="${path}/*.go"
+		fi
 		vetRes=$(go tool vet -shadow ${path})
 		if [ -n "${vetRes}" ]; then
 			echo -e "govet -shadow checking ${path} failed:\n${vetRes}"
@@ -148,6 +146,25 @@ function fmt_tests {
 		echo -e "license header checking failed:\n${licRes}"
 		exit 255
 	fi
+
+	echo "Checking commit titles..."
+	git log master..HEAD --oneline | while read l; do
+		pfx=`echo "$l" | cut -f2 -d' '`
+		if [ "$pfx" == "Merge" ]; then
+			# ignore "Merge pull" commits
+			continue
+		fi
+		if [ "$pfx" == "Revert" ]; then
+			# ignore revert commits
+			continue
+		fi
+		if ! [[ "$pfx" =~ :$ ]]; then
+			echo "$pfx"...
+			echo "Expected commit title format '<package>: <description>'"
+			echo "Got: $l"
+			exit 255
+		fi
+	done
 }
 
 function dep_tests {
@@ -163,9 +180,19 @@ function dep_tests {
 	fi
 }
 
+# Set up gopath so tests use vendored dependencies
+export GOPATH=${PWD}/gopath
+rm -rf $GOPATH/src
+mkdir -p $GOPATH
+ln -s ${PWD}/cmd/vendor $GOPATH/src
+
 # fail fast on static tests
+toggle_failpoints disable
 fmt_tests
 dep_tests
+
+# fail fast on static tests
+GO_BUILD_FLAGS="-a -v" etcd_build
 
 unit_tests
 if [ -n "$INTEGRATION" ]; then
